### ISSUE TITLE
用github action自动部署的话，那个last update在所有的页面都会显示最新commit的日期的

### ISSUE THREAD

**Issue by mini-full** [ckc-agc/study-assist#3]

**Comment by bowling233** [comment]
已于 b4a8722 修复。将 action 版本切换到 v4 并设置 `fetch depth` 为 0 即可，参考[mkdocs-git-revision 插件的 CI 设置部分](https://github.com/timvink/mkdocs-git-revision-date-localized-plugin#note-when-using-build-environments)。
